
package com.finstar.nsi.ws.drawingrequest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DrawingRequestService", targetNamespace = "http://finstar.com/nsi/ws/drawingrequest", wsdlLocation = "/wsdl/drawingrequest_ws.wsdl")
public class DrawingRequestService
    extends Service
{

    private final static URL DRAWINGREQUESTSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:/wsdl/drawingrequest_ws.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        DRAWINGREQUESTSERVICE_WSDL_LOCATION = url;
    }

    public DrawingRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DrawingRequestService() {
        super(DRAWINGREQUESTSERVICE_WSDL_LOCATION, new QName("http://finstar.com/nsi/ws/drawingrequest", "DrawingRequestService"));
    }

    /**
     * 
     * @return
     *     returns DrawingRequestPort
     */
    @WebEndpoint(name = "DrawingRequestService")
    public DrawingRequestPort getDrawingRequestService() {
        return (DrawingRequestPort)super.getPort(new QName("http://finstar.com/nsi/ws/drawingrequest", "DrawingRequestService"), DrawingRequestPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DrawingRequestPort
     */
    @WebEndpoint(name = "DrawingRequestService")
    public DrawingRequestPort getDrawingRequestService(WebServiceFeature... features) {
        return (DrawingRequestPort)super.getPort(new QName("http://finstar.com/nsi/ws/drawingrequest", "DrawingRequestService"), DrawingRequestPort.class, features);
    }

}
