
package com.finstar.nsi.ws.drawingrequest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1-b03-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "DrawingRequestPort", targetNamespace = "http://finstar.com/nsi/ws/drawingrequest")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DrawingRequestPort {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.finstar.nsi.ws.drawingrequest.WSOutputDrawingRequest
     */
    @WebMethod(action = "urn:makeDrawingRequest")
    @WebResult(name = "WSOutputDrawingRequest", targetNamespace = "http://finstar.com/nsi/ws/drawingrequest", partName = "parameters")
    public WSOutputDrawingRequest makeDrawingRequest(
        @WebParam(name = "WSInputDrawingRequest", targetNamespace = "http://finstar.com/nsi/ws/drawingrequest", partName = "parameters")
        WSInputDrawingRequest parameters);

}
