DROP TABLE BET_LOG;

CREATE TABLE BET_LOG (
  TXNO INT(11) NOT NULL auto_increment,
  TXTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TERMINAL VARCHAR(64) NOT NULL,
  GAME VARCHAR(64) NOT NULL,
  BET INT(11) NOT NULL,
  LINESBET INT(3) NOT NULL,
  FK_TXNO INT(11) NOT NULL,
  PRIMARY KEY (TXNO),
  INDEX(FK_TXNO),
  FOREIGN KEY (FK_TXNO) REFERENCES TRANSACTION_LOG(TXNO)
    ON DELETE CASCADE
)  ENGINE=INNODB;

DROP TABLE WIN_LOG;

CREATE TABLE WIN_LOG (
  TXNO INT(11) NOT NULL auto_increment,
  TXTS TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TERMINAL VARCHAR(64) NOT NULL,
  GAME VARCHAR(64) NOT NULL,
  STOP1 INT(3) NOT NULL,
  STOP2 INT(3) NOT NULL,
  STOP3 INT(3) NOT NULL,
  STOP4 INT(3) NOT NULL,
  STOP5 INT(3) NOT NULL,
  WIN   INT(9) NOT NULL,
  FREEGAMES INT(3) NOT NULL,
  FK_TXNO INT(11) NOT NULL,
  PRIMARY KEY (TXNO),
  INDEX(FK_TXNO),
  FOREIGN KEY (FK_TXNO) REFERENCES TRANSACTION_LOG(TXNO)
    ON DELETE CASCADE
)  ENGINE=INNODB;