CREATE TABLE TICKET_BATCH (
  LOTTERY_ID VARCHAR(32) NOT NULL,
  BATCH_ID VARCHAR(32) NOT NULL,
  TICKET_PRICE INT NOT NULL,
  TICKETS_FILE VARCHAR(256) NOT NULL,
  LAST_TICKET VARCHAR(32),
  STATUS ENUM('ACTIVE', 'ON_HOLD', 'COMPLETED') NOT NULL,
  PRIMARY KEY (LOTTERY_ID, BATCH_ID)
)  ENGINE=INNODB;
