DROP TABLE LOTTERY_METADATA;

DROP TABLE GAME_METADATA;

CREATE TABLE GAME_METADATA (
  GAME_ID VARCHAR(32) NOT NULL,
  GAME_TYPE VARCHAR(32) NOT NULL,
  NAME VARCHAR(256) NOT NULL,
  DENOM INT(5) NOT NULL,
  PRIMARY KEY(GAME_ID)
) ENGINE=INNODB;

CREATE TABLE LOTTERY_METADATA (
  LOTTERY_ID VARCHAR(32) NOT NULL,
  GAME_ID VARCHAR(32) NOT NULL,
  PRICE INTEGER,
  PRIMARY KEY(LOTTERY_ID, GAME_ID),
  INDEX(GAME_ID),
  FOREIGN KEY (GAME_ID) REFERENCES GAME_METADATA(GAME_ID)
    ON DELETE CASCADE
) ENGINE=INNODB;

INSERT INTO GAME_METADATA(GAME_ID, GAME_TYPE, NAME, DENOM) VALUES
("GBOR0122", "LONGTICKET", "Book of Ra", 1),
("GLLC0500", "LONGTICKET", "Lucky Lady Charm", 1),
("GDPL0100", "LONGTICKET", "Dolphin", 1),
("GBORSLOT", "SLOT", "Book of Ra - 2", 1),
("GBOR0123", "SHORTTICKET", "Book of Ra - 3", 1),
("GLLCSLOT", "SLOT", "Lucky Lady Charm - 2", 1),
("GDPLSLOT", "SLOT", "Dolphin - 2", 1),
("GMPL0500", "LONGTICKET", "MPL Game", 1),
("GSHL0500", "LONGTICKET", "SHL Game", 1);


COMMIT;

INSERT INTO LOTTERY_METADATA(GAME_ID, LOTTERY_ID, PRICE) VALUES
("GBOR0122", "LOT_BOR_NOBONUS", 500),
("GLLC0500", "LOT_LLC_NOBONUS", 500),
("GDPL0100", "LOT_LLC_NOBONUS", 100),
("GBOR0123", "LOT_BOR_NOBONUS", 500),
("GMPL0500", "LOT_MPL_NOBONUS", 500),
("GSHL0500", "LOT_SHL_NOBONUS", 500);

COMMIT;